datasets:
  - id: bulk_coding
    title: Bulk coding
    uri: localhost://datasets/bulk_coding.rds
    description: |
        Bulk RNA-sequencing of protein coding genes.

  - id: bulk_noncoding
    title: Bulk non-coding
    uri: localhost://datasets/bulk_noncoding.rds
    description: |
        Bulk RNA-sequencing of non-coding genes.

initial:
  - id: bulk_coding
    datasets:
      - bulk_coding
    title: Bulk coding
    uri: localhost://initial_states/bulk_coding.R
    description: |
      Initial configuration for the Bulk coding data set.

  - id: bulk_noncoding
    datasets:
      - bulk_noncoding
    title: Bulk non-coding
    uri: localhost://initial_states/bulk_noncoding.R
    description: |
      Initial configuration for the Bulk non-coding data set.
